export const GOOGLE_FONTS = [
  'Roboto',
  'Open Sans',
  'Montserrat',
  'Lato',
  'Poppins',
  'Inter',
  'Nunito',
  'Playfair Display',
  'Merriweather',
  'Oswald',
  'Raleway',
  'PT Sans',
  'Lora',
  'Quicksand',
  'Rubik',
  'Work Sans',
  'Fira Sans',
  'Barlow',
  'Mulish',
  'Questrial',
  'Bebas Neue',
  'Anton',
  'Dancing Script',
  'Pacifico',
  'Shadows Into Light',
  'Indie Flower',
  'Abril Fatface',
  'Permanent Marker',
  'Righteous',
  'Orbitron',
]
